unit Teste.Constantes;

interface

const
  TABELA_SEM_ALIAS = 'NOME_DA_TABELA';
  TABELA_COM_ALIAS = 'ANOME_DA_TABELA';
  TABELA_ALIAS = 'T_ALIAS';
  COLUNA_SEM_ALIAS = 'COLUNA';
  COLUNA_COM_ALIAS = 'ACOLUNA';
  COLUNA_NOME_VIRTUAL = 'NOME_VIRTUAL';

implementation

end.
